
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("520x720")
window.configure(bg = "#5B286D")


canvas = Canvas(
    window,
    bg = "#5B286D",
    height = 720,
    width = 520,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

def butClick(sub):
    f = open('logs.txt', 'a')
    f.write(' ' +sub)
    window.destroy()
    f.close()
    os.system('python subwindows/season.py')

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:butClick('Physics'),
    relief="flat"
)
button_1.place(
    x=260.0,
    y=39.0,
    width=186.0,
    height=39.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Chemistry'),
    relief="flat"
)
button_2.place(
    x=260.0,
    y=125.0,
    width=186.0,
    height=39.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Biology'),
    relief="flat"
)
button_3.place(
    x=260.0,
    y=211.0,
    width=186.0,
    height=39.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Mathematics-D'),
    relief="flat"
)
button_4.place(
    x=260.0,
    y=297.0,
    width=186.0,
    height=39.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Mathematics-Additional'),
    relief="flat"
)
button_5.place(
    x=260.0,
    y=383.0,
    width=186.0,
    height=39.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Computer Science'),
    relief="flat"
)
button_6.place(
    x=260.0,
    y=469.0,
    width=186.0,
    height=39.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('English'),
    relief="flat"
)
button_7.place(
    x=260.0,
    y=555.0,
    width=186.0,
    height=39.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: butClick('Bengali'),
    relief="flat"
)
button_8.place(
    x=260.0,
    y=641.0,
    width=186.0,
    height=39.0
)

canvas.create_text(
    11.0,
    299.0,
    anchor="nw",
    text="Select",
    fill="#FFFFFF",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    80.0,
    297.0,
    anchor="nw",
    text="your\n",
    fill="#FFFFFF",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    11.0,
    331.0,
    anchor="nw",
    text="required\n",
    fill="#FFFFFF",
    font=("JostRoman Regular", 24 * -1)
)

canvas.create_text(
    11.0,
    365.0,
    anchor="nw",
    text="subject:\n",
    fill="#FFFFFF",
    font=("JostRoman Regular", 24 * -1)
)
window.resizable(False, False)
window.mainloop()

